version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      O3/p71GEc4tXeyriAO+2FIekZXqWrRshBhWo1AoXYwYDUSWl8H7oJbzlcR8wf2qEFq0rB9I7qnD9OjOmJLPDtWyvqnJhJsJhfcO3DbWpPsVV2VsTGBJwLHfLGNhEtT2/EwU16ETOJfByANqIKKyq4fnljJNf1QZWxKmFwpHEVtr8yWd6TwOivTnKMxzAjY8zyO9RZZ222nRvdByCbMCw40uI1UygULTzz5MVzZUkHy+1fZ+gt+qZ+b3fYrJJRTed30OcTs3X1fd7HCS2MhblAW0YNN1KM/tHi8rba/+e6XXnrl/EekWGW0o8PfrqUFz11Lb209aKFxNGqZ8Vj0koBpbM3YkRwJprgHKjktDjiSmnwIsgm6zBedTr/KvuxdbttCY5+78tNdnxKuMADe+ntVwZpG3vJ43NzGAusqX/Emm1KMZAewpGEgDw8ia75ir84tTLRnCrat4nlRrFW0OEbgkhS5ZG0oV6eYlbfOpT+7xTvvZiC2QWc6cEYlHDAmHbfgO/2ea8Ab+DmUPL1pTpVLQNzu+1j6R9pgERN8KMKjYWPDiLV2Y9JZzdxJP4ohrCeGULe28fFgyl9ooGLBQIzuXCqUvcPUv/ZuF0uaA9Ke7Pg8ozrVDisnwxvsvtUC1Kjkns9ydnZ3BGoL5R56f7ZMYutrmm953Tee6o8rN/E68=
