sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: RzfhDVSVq8cqEShBsthZV5ABJ5D1qDwvG4E2DQ+dOK57yOqSBVpXxx7bgpYMEQPJPt2Pg2glYb2vG4PqDd9K2xoTsIk+veLraRBRKTEptEdsl/mhUnUFpiqYY2Tqm2d70kSSipcn+z9rKgzKy0GE0hSZkSXwH47XJi7hde45KJuQ0flF5mGpMSry8t9GkMO6/bVbWMaX2Cf8E/DBsytDYc6EJUZAykH0PH6ZSvk9j8rCqCJb7noFcyCcSlDHBC9/oMgL3LBCHv/PL0oecDvdc9JYHY0d9RA/EAYjZqMHKuGSLKc/pyB80vCH+aCjTjvKeTP0DLsNCmpDPPYp4hMxwh9dKeawRr04ipoQcbI66BIGTwpbRuaiw0Sdh9XJv5OTRJ9qlG7QuRZYNI5n6YXYyWMFChu5a1pLlNcg+kgtCtqjty7eOkuK4ECiKrnPT2x4+mKvszWfpiPlVoPJlw60oX2V2SUPk4PF/Fz5gZLKzdoo8UgrGOkVQdqToyf6TmEzuqNL6Jsapmgk/3JVfuE+zvczuj2vZQP85/m3br96ZlxWWoTCERDMC1H5z76stP7Ggj996WXF/dpW7DTlbEuFgyaGPit7RDaVSHtYfyrREUgwartZxFAbN1sLla7njc1j4pNE5cRN5wtwWXW1Y9XwafV3TTO0/0UMPrzStyLV5h4=
