version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      GfIjJcACfyoURtAqwBfyjI3bVm+tKonU2UP5bkSiZI7W0y9h+MdayVvqjE/nAh5R8oAqtB7zhafzuwOjl/jMrbMCc0jy98Qeg0AiNjvsLDyQ3T3gHHhG06fYKTsI7/6YjAn+qD+R0DlYdZPkuW882abHsbVDfnmSzp6504qOdSQUXW2UoMKZmIyVyUt1jd6OjksNQn+BgAIJxesTmom1iLHUIkyAoZyznOahKry4BLIyApiPjihdxyvwGG6QpeFt2wrB6fhJc40phH5t7cDQSIVHWxBhwKpYxsQ7cXaos9WUxjndVJFPlk/nCuSh3b/9lnMWNLSe7KpDB9W5LRwxLX3kpJKHPL5OvFLI/ikaMmNtK62bgFbjCuro/Afn3FFgaTgKLSopaCVH1uR9HU2QzzJ71K1+3ciQ2rO8m0Ug6TudI8j+bbkuDOoL9Eh7xw4TlR3rShNAex/yNniR+Th3UvZx59pOBkTYuoFTqQZ3thkXGsT3A1YwIRpvPnhuGb0pFsjRDSzcNgc6xIkA6+2PvjyX5K9sr/IgcyfMpa8O5OClme72DzKC5qLTzAVyg7b24ixDqjERq32wVrKxAE/mPBWheA3v+l3uOSUIMMj9TuNrinvyCkLB3x0U42LeOv/iA8dLsWC/nMYn3AAd95XSxU7Muy4mhmI6MXkvGys/usA=
