version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      nFfyttNRd4H9clfYJpJeuvNX8PWeychnYvZ0zdYXrr6TNHfBVLUKNb2zzx3zvbPGO7TKzVb9o+yi9iDcfJmPxIRkWNaukDNeAJY1yxkMIaXk5s9otakZR/QWBewrQsEwtcxj2tNRsOBF4ONVZerIEVlOIMmer3wf852DXGWxFuF7xWSh3adFEe1PjddxJEU4X8xnPfU2t921731BFVHPUNTzzyPxi1kPARTOGmDsnQzJZUgdPgaCEeREjGvFdGjvRPFW3F/1A1mdf2xinBkDTGxDlG0FYKzzzE0fhXJwH3sWLzq9FWrgxsVwWqfZkUTm5zN8iu7UEcs4RA3I/QOQORWVpn57+GvKfcpv3oqkmi4rvsm3WY7C63HydiUcLnOba+TYJUDbH5Px5E9UYcC1gHHW+dlydCUxsEW9RbWDFZkpuzGeexEwbyku38BtZcrnTBv9JIoi2dnGFS/g/pRPMx9hv8rORki0W5gtXvvZANcdKNt2YKDdpbE/Ppdz/gw4Woin2Ugz7YZmkY3dZAQ+DJtVtuA4/W8Te4IKrlLNJXV2W0Th/iuAgXjtER5oBV5SveJP/1aRe0wY903r5v6xsSte+9QkQe9xn8ebOQpO83him0wfQXLkzZXzg2pc6eOD2xxFc9jg7F3kru2FK1Lteq/x06mcgD1arISqOgiPZBQ=
